spring:
  application:
    name: bitforum
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/coinuser
    username: bitforum
    password: aaff11260407
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 초기엔 'update', 운영은 'validate'나 'none' 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true